stages:
  - build
  - deploy

build:
  stage: build
  image: samblaise/maturin
  script:
    - maturin build -i python3

publish3.5:
  stage: deploy
  image: samblaise/maturin:3.5
  only:
    - master
  script:
    - maturin publish -i python3.5 -u $user -p $password

publish3.6:
  stage: deploy
  image: samblaise/maturin:3.6
  only:
    - master
  script:
    - maturin publish -i python3.6 -u $user -p $password

publish3.7:
  stage: deploy
  image: samblaise/maturin:3.7
  allow_failure: true
  only:
    - master
  script:
    - maturin publish -i python3.7 -u $user -p $password

publish-latest:
  stage: deploy
  image: samblaise/maturin
  allow_failure: true
  only:
    - master
  script:
    - maturin publish -i python3 -u $user -p $password

      

