image: samblaise/pyo3-pack

stages:
  - deploy

publish:
  stage: deploy
  only:
    - master
  script:
    - rustup show
    - pyo3-pack --version
    - pyo3-pack publish -b cffi -u $user -p $password
