image: konstin2/pyo3-pack

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pyo3-pack build

publish:
  stage: deploy
  only:
    - master
  script:
    - pyo3-pack publish -u $user -p $password
